### ISSUE TITLE
Review commutable tutorial for accessibility

### ISSUE THREAD

**Issue by captainsafia** [nteract/docs#16]
Now that the commutable tutorial is finished, we should have a new contributor review it to see if the language and technical information is accurate and approachable.

### What do I need to do?

If you are a new contributor looking to take on this issue, thanks! You can start by visiting the commutable documentation page [here](http://nteract.io/docs/commutable/). Read through the tutorial and try to execute it. If there is a point where you feel confused or are unable to complete a tutorial step, write the down as an issue with the tutorial and we'll work with you to help fix it. Remember, this is the first published draft of the tutorial so if you experience difficulty while going through it, it's our fault not yours. 😄 

Once you've finished going through the material and writing down the issues, post a comment on this issue with a list of problems you found and we'll work with you to get them fixed!

### Where can I get help?

If you need help, feel free to comment on this issue and a project maintainer will come and assist you. If you'd like more chat-based support, you can join [our Slack](http://slack.nteract.in/) for assistance.

**Comment by temogen** [comment]
No real issues found. 

Haven't used node before, so had some minor bumps. 

I ended up opening up two console windows. One for the npm installs and the second for the node REPL. Might be beneficial for others to do the same, or do the installs before going into the REPL? Unless they were done in this sequence to emphasize how they are stored.

**Comment by willingc** [comment]
Thanks @temogen :cookie:

The feedback re: first time users of node is very helpful. Thanks!

**Comment by willingc** [comment]
Closed. Thanks to the contribution by @temogen.
