### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by jw56578** [nteract/docs#17]
Hello, found typo.
nforced on all methods. Let’s get **stated** with commutable. We’ll be working in the sh

**Comment by captainsafia** [comment]
Hello, @jw56578! Thanks for finding this issue and welcome to the nteract community!

Would you like to take a stab at fixing it or would you like to leave it for someone else?

**Comment by jw56578** [comment]
o yes, ill fix it.

**Comment by captainsafia** [comment]
> o yes, ill fix it.

Perfect! Thanks!
