### ISSUE TITLE
Create CONTRIBUTING.md or add to README

### ISSUE THREAD

**Issue by rgbkrk** [nteract/docs#4]
I'd love to know how to start working on the user guide (how do I build it?), how to add content, and get people on boarded to work together.

**Comment by willingc** [comment]
Hi folks,

If someone wants to move the content from [this file](https://github.com/nteract/user-guide/blob/master/content/contributor-guides/docs-contributor.md) (less the header) to a CONTRIBUTING.md or the README, that would be awesome-sauce.

**Comment by willingc** [comment]
Closing as #40 better covers our current process.
